---
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - follow_redirects: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets:
      - {{ env "NOMAD_ADDR_alrthttp" }}
rule_files:
- "alert.*.yml"
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - localhost:9090
- job_name: 'consul-prometheus-metrics'
  consul_sd_configs:
  - server: {{ env "HOST_IP" }}:8500
  relabel_configs:
  - source_labels: [__meta_consul_tags]
    regex: .*,prometheus-metrics,.*
    action: keep
  - source_labels: [__meta_consul_service]
    regex: katsdpcontroller-http|product-controller
    action: drop
  - source_labels: [__meta_consul_service]
    target_label: job
  - source_labels: [__meta_consul_node]
    target_label: instance
- job_name: 'consul-netdata-metrics'
  consul_sd_configs:
  - server: {{ env "HOST_IP" }}:8500
  relabel_configs:
  - source_labels: [__meta_consul_tags]
    regex: .*,netdata-metrics,.*
    action: keep
  - source_labels: [__meta_consul_service]
    target_label: job
  - source_labels: [__meta_consul_node]
    target_label: instance
